export const STORIES=[
    {
        id:"1",
        username:"adhi",
        avatar:"https://t3.ftcdn.net/jpg/02/99/04/20/360_F_299042079_vGBD7wIlSeNl7vOevWHiL93G4koMM967.jpg",
        hasStory:false,
    },
    {
        id:"2",
        username:"pawan",
        avatar:"https://t3.ftcdn.net/jpg/02/43/12/34/360_F_243123463_zTooub557xEWABDLk0jJklDyLSGl2jrr.jpg",
        hasStory:true,
    },
    {
        id:"3",
        username:"sarayu",
        avatar:"https://media.istockphoto.com/id/1132928597/photo/portrait-of-nice-cute-smart-clever-attractive-beautiful-cheerful-glad-positive-wavy-haired.jpg?s=612x612&w=0&k=20&c=jcUVffv6QeE5MnP7BnrmjJ8-gcjEajclqyMEg9Z6uwI=",
        hasStory:false,
    },
    {
        id:"4",
        username:"sameers",
        avatar:"https://thumbs.dreamstime.com/b/young-african-woman-arms-out-shrugging-her-shoulders-saying-who-cares-what-now-young-african-woman-arms-out-shrugging-203001518.jpg",
        hasStory:false,
    },
    {
        id:"5",
        username:"sahas",
        avatar:"https://thumbs.dreamstime.com/b/satisfied-overjoyed-african-american-guy-showing-thumb-up-like-sign-satisfied-overjoyed-african-american-guy-showing-thumb-up-like-235272754.jpg",
        hasStory:false,
    },
    {
        id:"6",
        username:"megamall",
        avatar:"https://static.toiimg.com/photo/44856215/.jpg",
        hasStory:false,
    },
    {
        id:"7",
        username:"chiru",
        avatar:"https://cdn.shopify.com/s/files/1/0896/6753/5157/files/1-15_2018-08.jpg",
        hasStory:true,
    },
    {
        id:"8",
        username:"thala",
        avatar:"https://www.shutterstock.com/image-photo/portrait-man-wearing-pink-shirt-260nw-2258755273.jpg",
        hasStory:false,
    },
    {
        id:"9",
        username:"heisenberg",
        avatar:"https://t3.ftcdn.net/jpg/02/99/04/20/360_F_299042079_vGBD7wIlSeNl7vOevWHiL93G4koMM967.jpg",
        hasStory:true,
    },
]